pygmentsUseClasses: true
pygmentsCodefences: true

baseurl: "https://lust.dev/"
title: lust.dev
languageCode: en-us
copyright: "Joe Lust"
theme: ghostwriter
googleAnalytics: "UA-17498476-1"
disqusShortname: lustforge
relativeURLs: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: "Joseph Lust"
  profile: ""

taxonomies:
  tag: tags

contentDir: content

params:
  mainSections:
    - post
  intro: true
  headline: lust.dev
  description: "a cloud engineering blog"
  github: "https://github.com/twistedpair"
#  gitlab: "https://gitlab.com/XXX"
  linkedin: "https://linkedin.com/in/josephlust"
  twitter: "https://twitter.com/lustcoder"
  stackoverflow: "https://stackoverflow.com/users/564157/joseph-lust"
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "2 Jan '06"
  readingTime: true
  readingTimeText: "⏰"

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Tags
      url: /tags
      weight: 2
    - name: About J. Lust
      url: /page/about/
      weight: 3
