baseurl = "https://lustforge.com/"
languageCode = "en-us"
title = "LustForge"
copyright = "Joseph Lust"
description = "what Lust hath wrought"
theme = "ghostwriter"
googleAnalytics = "UA-17498476-1"
disqusShortname = "lustforge"

[Author]
    name = "Joseph Lust"
    profile = "https://stackoverflow.com/users/564157/joseph-lust"

[Taxonomies]
    tag = "tags"
    category = "categories"

[Params]
    copyrightStartYear = "2009"
    favicon = "favicon.png"
    intro = true # hide site title
    headline = "LustForge"
    defaultPostImage = "/img/lustforge_key_default.png"
    description = "what Lust hath wrought"
    organization = "LustForge.com"
    github = "https://github.com/twistedpair"
    linkedin = "https://www.linkedin.com/in/josephlust"
    twitter = "https://twitter.com/lustcoder"
    stackoverflow = "https://stackoverflow.com/users/564157/joseph-lust"
    rss = true

#    highlight = "atelier-forest.dark"
#    highlight = "atelier-dune.dark"
#    highlight = "monokai"
    highlight = "obsidian"
    pygmentsCodeFences = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"
